version: "3.9"
services:
  view:
    build: ./view
    ports:
      - "80:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
  api:
    build: ./api/AparitoPrimeNumbersAPI
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEVELOPMENT_CORS_ORIGIN=http://localhost
